/**
 * Procedural lightning generation using the midpoint-displacement /
 * random-walk-with-smoothing algorithm (Hoffman, 2013 — the canonical
 * technique for game-quality 2D lightning).
 *
 * Real lightning isn't a small number of big corners — it's hundreds
 * of tiny correlated displacements along a mostly-straight line, with
 * displacement smoothed against the previous step so adjacent segments
 * never form sharp angles. An envelope tapers displacement near the
 * endpoint so the bolt converges cleanly.
 *
 * Branches are generated by the same algorithm rooted at random
 * midpoints of the trunk, fired off at small angles from the local
 * direction with a fraction of the trunk's length.
 */

export type Pt = [number, number];

/** mulberry32: small fast deterministic PRNG. Same seed → same bolt. */
export function mulberry32(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4_294_967_296;
  };
}

interface BoltResult {
  points: Pt[];
}

function generateBolt(
  source: Pt,
  dest: Pt,
  sway: number,
  rng: () => number,
  density = 4,
): BoltResult {
  const tx = dest[0] - source[0];
  const ty = dest[1] - source[1];
  const length = Math.hypot(tx, ty);
  if (length === 0) return { points: [source] };

  const nx = ty / length;
  const ny = -tx / length;

  const samples = Math.max(8, Math.floor(length / density));
  const positions: number[] = [0];
  for (let i = 0; i < samples; i++) positions.push(rng());
  positions.sort((a, b) => a - b);

  const jaggedness = 1 / sway;

  let prevDisp = 0;
  const points: Pt[] = [source];

  for (let i = 1; i < positions.length; i++) {
    const pos = positions[i];
    const scale = length * jaggedness * (pos - positions[i - 1]);
    const envelope = pos > 0.95 ? 20 * (1 - pos) : 1;

    let disp = (rng() * 2 - 1) * sway;
    disp -= (disp - prevDisp) * (1 - scale);
    disp *= envelope;

    points.push([
      source[0] + pos * tx + disp * nx,
      source[1] + pos * ty + disp * ny,
    ]);
    prevDisp = disp;
  }

  points.push(dest);
  return { points };
}

function generateBranches(
  mainPoints: Pt[],
  count: number,
  rng: () => number,
  sway = 30,
): Pt[][] {
  const branches: Pt[][] = [];
  const minIdx = Math.floor(mainPoints.length * 0.15);
  const maxIdx = Math.floor(mainPoints.length * 0.85);

  for (let i = 0; i < count; i++) {
    const idx = minIdx + Math.floor(rng() * Math.max(1, maxIdx - minIdx));
    const origin = mainPoints[idx];

    const next = mainPoints[Math.min(idx + 4, mainPoints.length - 1)];
    const dx = next[0] - origin[0];
    const dy = next[1] - origin[1];
    const mag = Math.hypot(dx, dy) || 1;
    const ux = dx / mag;
    const uy = dy / mag;

    const sign = rng() < 0.5 ? -1 : 1;
    const angle = sign * (0.35 + rng() * 0.6);
    const c = Math.cos(angle);
    const s = Math.sin(angle);
    const rx = ux * c - uy * s;
    const ry = ux * s + uy * c;

    const branchLen = 90 + rng() * 220;
    const dest: Pt = [origin[0] + rx * branchLen, origin[1] + ry * branchLen];

    const { points } = generateBolt(origin, dest, sway, rng, 5);
    branches.push(points);
  }

  return branches;
}

export interface Lightning {
  trunk: Pt[];
  branches: Pt[][];
}

/** Generate one full lightning strike — trunk + branches as point arrays. */
export function generateLightning(
  seed: number,
  source: Pt,
  dest: Pt,
  sway = 90,
  branchCount = 7,
): Lightning {
  const rng = mulberry32(seed);
  const main = generateBolt(source, dest, sway, rng, 4);
  const branches = generateBranches(main.points, branchCount, rng, 30);
  return { trunk: main.points, branches };
}

/** Stroke a polyline through a list of points on a canvas. */
export function strokePoints(ctx: CanvasRenderingContext2D, pts: Pt[]) {
  if (pts.length < 2) return;
  ctx.beginPath();
  ctx.moveTo(pts[0][0], pts[0][1]);
  for (let i = 1; i < pts.length; i++) ctx.lineTo(pts[i][0], pts[i][1]);
  ctx.stroke();
}
